# Generated by Django 4.1.2 on 2022-12-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
