# Generated by Django 4.1.2 on 2022-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RB', 'Restobar'), ('CF', 'Cafe'), ('CN', 'Canteen'), ('NC', 'Night club'), ('B', 'Bar')], default='B', max_length=50),
        ),
    ]
